### ISSUE TITLE
Asking for opinion 

### ISSUE THREAD

**Issue by jnthas** [jnthas/Improv-WiFi-Library#1]
@balloob I'm working in a Arduino library for Improv WiFi. I would like to hear your opinion, please. Some points I'm considering:

- I'm not sure using `std::string` or `String`
- Improve the way to require the user to pass setDeviceInfo() parameters
- I'm allowing the user to customize the connectWifi() method and also receive callbacks when an error or success occurs
- I'm thinking in remove `improv.cpp` class as I'm passing the SDK to the ImprovWiFi class.

**Comment by balloob** [comment]
These are more questions for @jesserockz as he wrote the SDK and implementation for ESPHome.

**Comment by jesserockz** [comment]
`String` is defined by Arduino and using it forces a library to be Arduino only. It's there in the improv sdk but preprocessed out when not using Arduino so the sdk would be compatible with other frameworks, eg `esp-idf` where `std::string` can be used.

**Comment by jnthas** [comment]
Right. I saw the preprocessor but in this library I will have to use this practice a lot, it can get confusing. I think I can prioritize `char*` for public methods and use `std::string` internally.

**Comment by jnthas** [comment]
@jesserockz if you have any other consideration please let me know!
