### ISSUE TITLE
Improv BLE example

### ISSUE THREAD

**Issue by clau-bucur** [jnthas/Improv-WiFi-Library#6]
Trying to use Improv with BLE adoption, but can't find any examples other than the ESPHome implementation (which is a bit too complex for my limited understanding).

Do you have some simple example, similar to the Serial, of BLE?

**Comment by jnthas** [comment]
Same here. My intention was create a library for Serial and BLE but I couldn't find a good example using BLE and I couldn't make it work as expected.

**Comment by clau-bucur** [comment]
Pff, sad to hear that! I asked the same on the SDK repo, maybe we have luck there.
Thank you!
