### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ldijkman** [jnthas/Improv-WiFi-Library#7]
Thank you for the info

https://ldijkman.github.io/async-esp-fs-webserver/

video of improv test
https://youtu.be/14cINXIzMI8

![Screenshot from 2024-02-25 10-00-37](https://github.com/jnthas/Improv-WiFi-Library/assets/45427770/8a15cdc3-0d50-430f-bbe0-1839f8898354)

**Comment by ldijkman** [comment]
Thank you very much for your examples

https://youtu.be/tgL_leDr7Ls

should have one more field
- ssid
- password
- mdns adres = garden kitchen toilet living etcetera

**Comment by jnthas** [comment]
Glad to see it worked!
